# Generated by Django 5.2 on 2025-04-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_comment_user_post_tags_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Default Title', unique=True),
            preserve_default=False,
        ),
    ]
