# Generated by Django 5.1.6 on 2025-05-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
